name: Node.js Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.11
          # Este registry se usa solo para la instalación de dependencias,
          # no afecta el build
          registry-url: https://registry.npmjs.org/

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.14.0

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: |
          pnpm --filter @dialog-fn/core build && \
          pnpm --filter @dialog-fn/react build && \
          pnpm --filter @dialog-fn/svelte build

      - name: Upload packages as artifact
        uses: actions/upload-artifact@v3
        with:
          name: packages-build
          path: packages/  # Se sube toda la carpeta "packages"

  publish-gpr:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Publish @dialog-fn/react to GitHub Packages
            package: packages/react
          - name: Publish @dialog-fn/svelte to GitHub Packages
            package: packages/svelte
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: packages-build
          path: .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.11
          registry-url: https://npm.pkg.github.com/

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.14.0

      - name: Publish to GitHub Packages
        working-directory: ${{ matrix.package }}
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Publish @dialog-fn/react to NPM
            package: packages/react
          - name: Publish @dialog-fn/svelte to NPM
            package: packages/svelte
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: packages-build
          path: .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.11
          registry-url: https://registry.npmjs.org/

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.14.0

      - name: Publish to NPM
        working-directory: ${{ matrix.package }}
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

